/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author sivaranjanisuresh
 */
public class SystemAdminMain extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminMain
     */
    public SystemAdminMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmPatient = new javax.swing.JButton();
        btnmDoctor = new javax.swing.JButton();
        btnmCommunity = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblhospAdmin = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 800));

        btnmPatient.setText("Manage Patient");
        btnmPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmPatientActionPerformed(evt);
            }
        });

        btnmDoctor.setText("Manage Doctor");

        btnmCommunity.setText("Community Manager");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("SYSTEM ADMIN LOGIN");

        lblhospAdmin.setText("Hospital Administrator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblTitle)
                            .addGap(211, 211, 211))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnmPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnmCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                .addComponent(lblhospAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(304, 304, 304)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTitle)
                .addGap(43, 43, 43)
                .addComponent(btnmPatient)
                .addGap(33, 33, 33)
                .addComponent(btnmDoctor)
                .addGap(28, 28, 28)
                .addComponent(btnmCommunity)
                .addGap(26, 26, 26)
                .addComponent(lblhospAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(507, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnmPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmPatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmCommunity;
    private javax.swing.JButton btnmDoctor;
    private javax.swing.JButton btnmPatient;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblhospAdmin;
    // End of variables declaration//GEN-END:variables
}
